
# oss-configserver with a internal git service, for development, Use H2 as datasource.

version: '2.1'
services:
  oss-configserver:
    image: home1oss/oss-configserver:${PROJECT_VERSION:-latest}
    restart: always
    command: []
    container_name: ${EUREKA_INSTANCE_HOSTNAME:-oss-configserver.local}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:-oss-configserver.local}
    ports:
    - "${EUREKA_INSTANCE_NONSECUREPORT:-8888}:${SERVER_PORT:-8888}"
    volumes:
    - volume-oss-configserver:/tmp
    - volume-oss-configserver:/root/.oss
#    - ${SPRING_CLOUD_CONFIG_SERVER_DEPLOYKEY_PATH}/production-deploy_key:/root/production-deploy_key
#    - ${SPRING_CLOUD_CONFIG_SERVER_DEPLOYKEY_PATH}/production-keystore.jks:/root/production-keystore.jks
    environment:
    - APP_ADMINPUBLICKEY=${APP_ADMINPUBLICKEY:-RSA1024_PUB_X509:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/gmBcdQZxiQmhQrP1awAZuuOl4snl7cEV8n65osVO7CdqxXG5mUYNVr6siwuTm/SsmBV+86JISlzvMK/Bxwsmf/ApZicgItChmDuU9TCaZIksqnpbtONnCm/sHWwa/2hqPTjdc0LC+jQ/FCU2b9vpbSId0Wg28/gtoGaLWbsm/QIDAQAB}
    - DB_ADDR=${DB_ADDR:-~/.oss/oss-configserver/h2}
    - DB_NAME=${DB_NAME:-oss-configserver}
    - DB_PORT=${DB_PORT:-3306}
    - DB_PASS=${DB_PASS:-user_pass}
    - DB_USER=${DB_USER:-user}
    - ENCRYPT_KEYSTORE_ALIAS=${ENCRYPT_KEYSTORE_ALIAS:-key_alias}
    - ENCRYPT_KEYSTORE_LOCATION=${ENCRYPT_KEYSTORE_LOCATION:-classpath:keystore.jks}
    - ENCRYPT_KEYSTORE_PASSWORD=${ENCRYPT_KEYSTORE_PASSWORD:-store_pass} # store password
    - ENCRYPT_KEYSTORE_SECRET=${ENCRYPT_KEYSTORE_SECRET:-key_pass} # key password
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@oss-eureka.local:8761/eureka/}
    - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME:-oss-configserver.local}
    - EUREKA_INSTANCE_NONSECUREPORT=${EUREKA_INSTANCE_NONSECUREPORT:-8888}
    - GIT_HOST=${GIT_HOST:-gitlab.internal}
    - GIT_SSH_PORT=${GIT_SSH_PORT:-22}
    - GIT_PREFIX=${GIT_PREFIX:-git@gitlab.internal:home1-oss}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-admin_pass}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-oss-configserver.local}
    - SERVER_PORT=${SERVER_PORT:-8888}
    - SPRING_CLOUD_CONFIG_SERVER_COMMONCONFIG_APPLICATION=${SPRING_CLOUD_CONFIG_SERVER_COMMONCONFIG_APPLICATION:-common}
    - SPRING_CLOUD_CONFIG_SERVER_COMMONCONFIG_LABEL=${SPRING_CLOUD_CONFIG_SERVER_COMMONCONFIG_LABEL:-develop}
    - SPRING_CLOUD_CONFIG_SERVER_DEPLOYKEY=${SPRING_CLOUD_CONFIG_SERVER_DEPLOYKEY:-classpath:default_deploy_key} # changeme
    - SPRING_CLOUD_CONFIG_SERVER_DEFAULTLABEL=${SPRING_CLOUD_CONFIG_SERVER_DEFAULTLABEL:-develop}
    - SPRING_CLOUD_CONFIG_SERVER_DEFAULTPROFILE=${SPRING_CLOUD_CONFIG_SERVER_DEFAULTPROFILE:-default}
    - SPRING_CLOUD_CONFIG_SERVER_MONITOR_BITBUCKET_ENABLED=${SPRING_CLOUD_CONFIG_SERVER_MONITOR_BITBUCKET_ENABLED:-false}
    - SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITHUB_ENABLED=${SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITHUB_ENABLED:-false}
    - SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITLABPATH_ENABLED=${SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITLABPATH_ENABLED:-true}
    - SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITLAB_ENABLED=${SPRING_CLOUD_CONFIG_SERVER_MONITOR_GITLAB_ENABLED:-false}
    - SPRING_CLOUD_CONFIG_SERVER_MONITOR_WHITELIST=${SPRING_CLOUD_CONFIG_SERVER_MONITOR_WHITELIST} # changeme
    - SPRING_PROFILES_ACTIVE=${ENV:-development}.env
    - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST:-cloudbus.local} # changeme
    - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD:-user_pass} # changeme
    - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT:-5672}
    - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME:-user} # changeme
    external_links:
    - oss-eureka.local:oss-eureka.local
    - cloudbus.local:cloudbus.local



volumes:
  volume-oss-configserver: {}

networks:
  default:
    external:
      name: oss-network
